# -*- coding: utf-8 -*-
"""lithium_predictor_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGC5yKqFxbPctstQZWlHvbm-KbwfG4ik
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from catboost import CatBoostRegressor

# Load trained models
model = joblib.load("catboost_model.pkl")
kmeans = joblib.load("kmeans_model.pkl")

# Feature names
numerical_features = ['LATITUDE', 'LONGITUDE', 'Na', 'K', 'Mg', 'Ca', 'Sr', 'Cl', 'TDS', 'PH', 'I', 'B']
categorical_features = ['FORMATION', 'BASIN']  # RegionCluster will be auto-added

st.set_page_config(page_title="Lithium Predictor", layout="centered")
st.title("🔮 Real-Time Lithium Predictor (CatBoost Model)")

st.markdown("Enter the following input parameters to predict lithium concentration (mg/L).")

# User input collection
user_input = {}

# Numerical inputs
for col in numerical_features:
    user_input[col] = st.number_input(f"{col}", value=0.0)

# Simplified formation options for dropdown
formation_mapping = {
    "Wolfcamp (All)": "Wolfcamp",
    "Clear Fork (All)": "Clear Fork",
    "Devonian (All)": "Devonian",
    "Ellenburger (All)": "Ellenburger",
    "San Andres (All)": "San Andres",
    "Delaware (All)": "Delaware",
    "Canyon (All)": "Canyon",
    "Strawn (All)": "Strawn",
    "Pennsylvanian (All)": "Pennsylvanian",
    "Fusselman": "Fusselman",
    "Cisco": "Cisco",
    "Cherry Canyon": "Cherry Canyon",
    "Glorieta": "Glorieta",
    "Dean": "Dean",
    "Spraberry": "Spraberry",
    "Atoka": "Atoka",
    "Montoya Ellenburger": "Montoya Ellenburger",
    "Bend": "Bend",
    "Lo Abo": "Lo Abo",
    "Bell Canyon": "Bell Canyon",
    "Unknown": "Unknown"
}

# Show friendly dropdown
user_friendly_formations = list(formation_mapping.keys())
selected_ui_value = st.selectbox("FORMATION", user_friendly_formations, index=user_friendly_formations.index("Wolfcamp (All)"))

# Map dropdown value to what model expects
user_input["FORMATION"] = formation_mapping[selected_ui_value]

# Prefill BASIN (no dropdown needed)
user_input["BASIN"] = "Permian"

# Auto-calculate RegionCluster
latlon = [[user_input["LATITUDE"], user_input["LONGITUDE"]]]
region_cluster = int(kmeans.predict(latlon)[0])
user_input["RegionCluster"] = region_cluster

st.markdown(f"🧭 **Auto-Assigned Region Cluster**: `{region_cluster}`")

# Make prediction
if st.button("🔍 Predict Lithium"):
    input_df = pd.DataFrame([user_input])
    prediction = model.predict(input_df)[0]
    st.success(f"🧪 Predicted Lithium Concentration: **{prediction:.2f} mg/L**")
